### ISSUE TITLE
Graphical version of dozdc crashes when trying to do computations

### ISSUE THREAD

**Issue by trevorld** [dgoodmaniii/dozenal#4]
For example after I type ``45 * 25 =`` the window crashes and I get the following error in my terminal::

    trevorld@trevorld-Bonobo-Extreme:~/bin$ dozdc -v
    In fl_read_pixmapfile() [pixmap.c:632]: error reading logo_shapes_dozenal.xpm (Can't open)
    X81
    *** stack smashing detected ***: dozdc terminated
    Aborted

Non-graphical version seems to run fine.

**Comment by dgoodmaniii** [comment]
I can't duplicate this at all, and can't explain what's happening.  I can surmise, purely speculatively, that xforms is throwing some crazy error at the operating system because it can't find the logo file.  It's probably better just to remove that from the program entirely.  Do you find the same error when running it in the local directory where logo_shapes_dozenal.xpm is located?

**Comment by trevorld** [comment]
Still crashes but I no longer get the "error reading logo_shapes_dozenal.xpm" warning/error.  Not sure what the issue could be. It obviously can compute the answer ``X81`` fine because its printed out to standard output and it doesn't throw an error in non-graphical dozdc nor graphical gdozdc (if ran in local directory)::
```

trevorld@trevorld-Bonobo-Extreme:~/tmp/dozenal/dozenal/dozdc$ dozdc -v
X81
*** stack smashing detected ***: dozdc terminated
Aborted
```

**Comment by trevorld** [comment]
I suspect now that it might be due to the libxpm-dev in Ubuntu's repositories.   The configuration for xforms had the following note which I didn't pay too much attention to earlier::

```
== Version . of the Xpm library is a bit old.
   If you experience strange crashes with xforms, try to upgrade
   to at least version 4.7 (aka 3.4g).
   If you have installed a newer version of the library, check whether you
   have an old xpm.h header file in your include path.
```

It seems a pain to manually install libxpm (i.e. they don't distribute binaries relying instead on distributions like Ubuntu and the source doesn't have a configure file and autoconf says I need to install other libraries in order to run it in order to build a configure file in order to make it).

https://github.com/freedesktop/libXpm
