### ISSUE TITLE
Can't run ``make install`` version of gdozdc 

### ISSUE THREAD

**Issue by trevorld** [dgoodmaniii/dozenal#5]
After updating the image file in gdozdc.pl to ``logo_shapes_mask.xbm`` (since ``logo_shapes_dozenal.xbm`` doesn't exist) the ``make prefix=$HOME`` compiled version located in dozdc directory now runs but when I try to use the ``make prefix=$HOME install`` version in ``~/bin`` I get the error message::

    couldn't read bitmap file "logo_shapes_dozenal.xbm": No such file or directory at /home/trevorld/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Tk/Image.pm line 21.

**Comment by dgoodmaniii** [comment]
Simply removed the image statements from the program, which doesn't really benefit the program at all.  This should now function properly.
